-- Enable pgvector for clustering embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- Table: search_terms
-- Stores the original row data and AI enrichments
CREATE TABLE IF NOT EXISTS search_terms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID,
    search_term TEXT NOT NULL,
    cost DECIMAL(12, 2) DEFAULT 0.00,
    clicks INTEGER DEFAULT 0,
    conversions INTEGER DEFAULT 0,
    cpc DECIMAL(12, 2),
    conversion_rate DECIMAL(5, 2),
    intent TEXT, -- HIGH, MEDIUM, LOW
    decision TEXT, -- KEEP, NEGATIVE
    reason TEXT, -- Explanation for the decision
    cluster_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: reports
-- Metadata for each uploaded CSV and aggregated results
CREATE TABLE IF NOT EXISTS reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    filename TEXT,
    total_spend DECIMAL(12, 2),
    waste_spend DECIMAL(12, 2),
    efficiency_score DECIMAL(5, 2), -- (converting_terms / total_terms) * 100
    waste_score DECIMAL(5, 2), -- (waste_spend / total_spend) * 100
    intent_score DECIMAL(5, 2), -- (high_intent_terms / total_terms) * 100
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: negative_keywords
-- Final list of terms to be added as negative keywords
CREATE TABLE IF NOT EXISTS negative_keywords (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    keyword TEXT NOT NULL,
    phase TEXT, -- e.g., Phase 1: High Spend, Phase 2: Low Intent
    reason TEXT,
    report_id UUID REFERENCES reports(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: clusters
-- Semantic clusters generated by embeddings
CREATE TABLE IF NOT EXISTS clusters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cluster_name TEXT,
    common_pattern TEXT, -- AI-summarized pattern for the cluster
    avg_cpc DECIMAL(12, 2),
    total_conversions INTEGER,
    report_id UUID REFERENCES reports(id) ON DELETE CASCADE
);

-- (Optional) Add foreign key link from search_terms to reports
ALTER TABLE search_terms ADD CONSTRAINT fk_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE;
